# reporting/branding.py
from datetime import datetime
import pandas as pd

class Branding:
    """Privileged Rapper Inc. branding utilities"""
    
    COMPANY_NAME = "Privileged Rapper Inc."
    COMPANY_SLOGAN = "Enterprise Security Platform"
    COPYRIGHT = f"© {datetime.now().year} All Rights Reserved"
    
    @staticmethod
    def get_report_header():
        """Get standardized report header"""
        return {
            'company_name': Branding.COMPANY_NAME,
            'slogan': Branding.COMPANY_SLOGAN,
            'copyright': Branding.COPYRIGHT,
            'generated_at': datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            'footer_text': f"GENERATED BY {Branding.COMPANY_NAME.upper()}"
        }
    
    @staticmethod
    def apply_branding_to_dataframe(df):
        """Apply branding to pandas DataFrame"""
        # Add metadata as first row
        metadata_row = {
            'Note': f'Report generated by {Branding.COMPANY_NAME} - {Branding.COPYRIGHT}'
        }
        
        # Add metadata to all columns if possible
        for col in df.columns:
            metadata_row[col] = ''  # Empty for other columns
        
        # Convert to DataFrame and concatenate
        metadata_df = pd.DataFrame([metadata_row])
        branded_df = pd.concat([metadata_df, df], ignore_index=True)
        
        return branded_df
    
    @staticmethod
    def get_color_scheme():
        """Get company color scheme"""
        return {
            'primary': '#1f77b4',
            'secondary': '#ff7f0e', 
            'success': '#2ca02c',
            'warning': '#ffbb78',
            'danger': '#d62728',
            'dark': '#2c3e50',
            'light': '#ecf0f1'
        }