# reporting/csv_generator.py
import pandas as pd
from datetime import datetime
import os

class CSVReportGenerator:
    def __init__(self, db):
        self.db = db
    
    def generate_detailed_export(self, config):
        """Generate detailed CSV export"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"PrivilegedRapper_Export_{timestamp}.csv"
        filepath = os.path.join("reports", filename)
        
        # Create reports directory if it doesn't exist
        os.makedirs("reports", exist_ok=True)
        
        # Get data based on config
        query = {}
        if config.get('start_date'):
            query['created_at'] = {'$gte': config['start_date']}
        
        findings = list(self.db.findings.find(query))
        
        # Convert to DataFrame
        data = []
        for finding in findings:
            data.append({
                'Finding_ID': str(finding['_id']),
                'Title': finding['title'],
                'Description': finding['description'],
                'Risk_Level': finding['risk_level'],
                'Category': finding.get('category', 'Unknown'),
                'CVSS_Score': finding.get('cvss_score', 'N/A'),
                'Evidence': finding.get('evidence', '')[:500],  # Limit length
                'Mitigation': finding.get('mitigation', ''),
                'Status': finding.get('status', 'open'),
                'Created_Date': finding.get('created_at', datetime.now()).strftime('%Y-%m-%d %H:%M:%S'),
                'Assigned_To': finding.get('assigned_to', 'Unassigned')
            })
        
        df = pd.DataFrame(data)
        
        # Add metadata row
        metadata = {
            'Finding_ID': 'REPORT_METADATA',
            'Title': f"Privileged Rapper Inc. Export - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            'Description': f"Generated by: {config['generated_by']}",
            'Risk_Level': 'N/A',
            'Category': 'Export',
            'CVSS_Score': 'N/A',
            'Evidence': f"Total findings: {len(findings)}",
            'Mitigation': 'CONFIDENTIAL - PRIVILEGED RAPPER INC.',
            'Status': 'COMPLETED',
            'Created_Date': 'N/A',
            'Assigned_To': 'SYSTEM'
        }
        
        df_metadata = pd.DataFrame([metadata])
        df = pd.concat([df_metadata, df], ignore_index=True)
        
        # Export to CSV
        df.to_csv(filepath, index=False, encoding='utf-8')
        
        return filepath