# reporting/pdf_generator.py
from reportlab.lib.pagesizes import letter, A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.pdfgen import canvas
from datetime import datetime
import os

class PDFReportGenerator:
    def __init__(self, db):
        self.db = db
        self.styles = getSampleStyleSheet()
        self.setup_custom_styles()
    
    def setup_custom_styles(self):
        """Setup custom styles for professional reporting"""
        self.styles.add(ParagraphStyle(
            name='CompanyHeader',
            parent=self.styles['Heading1'],
            fontSize=16,
            textColor=colors.HexColor('#1f77b4'),
            spaceAfter=12,
            alignment=1  # Center aligned
        ))
        
        self.styles.add(ParagraphStyle(
            name='FindingTitle',
            parent=self.styles['Heading2'],
            fontSize=12,
            textColor=colors.red,
            spaceAfter=6
        ))
        
        self.styles.add(ParagraphStyle(
            name='Footer',
            parent=self.styles['Normal'],
            fontSize=8,
            textColor=colors.gray,
            alignment=1
        ))
    
    def generate_comprehensive_report(self, config):
        """Generate comprehensive PDF report"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"PrivilegedRapper_Report_{timestamp}.pdf"
        filepath = os.path.join("reports", filename)
        
        # Create reports directory if it doesn't exist
        os.makedirs("reports", exist_ok=True)
        
        doc = SimpleDocTemplate(
            filepath,
            pagesize=A4,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=72
        )
        
        story = []
        
        # Add cover page
        story.extend(self.create_cover_page(config))
        
        # Add executive summary
        story.extend(self.create_executive_summary(config))
        
        # Add detailed findings
        story.extend(self.create_findings_section(config))
        
        # Add mitigation recommendations
        story.extend(self.create_mitigation_section(config))
        
        # Build PDF
        doc.build(story, onFirstPage=self.add_footer, onLaterPages=self.add_footer)
        
        return filepath
    
    def create_cover_page(self, config):
        """Create professional cover page"""
        elements = []
        
        # Company logo (would be replaced with actual logo)
        # logo = Image("assets/images/logo.png", width=2*inch, height=2*inch)
        # elements.append(logo)
        # elements.append(Spacer(1, 0.5*inch))
        
        # Title
        title = Paragraph("PRIVILEGE ESCALATION SECURITY REPORT", self.styles['CompanyHeader'])
        elements.append(title)
        elements.append(Spacer(1, 0.3*inch))
        
        # Report details
        details = [
            ["Report Type:", config['report_type']],
            ["Generated By:", config['generated_by']],
            ["Generation Date:", datetime.now().strftime("%Y-%m-%d %H:%M:%S")],
            ["Time Period:", "Last 30 days" if config.get('start_date') else "All time"]
        ]
        
        details_table = Table(details, colWidths=[2*inch, 4*inch])
        details_table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('LINEBELOW', (0, 0), (-1, -1), 1, colors.grey),
        ]))
        
        elements.append(details_table)
        elements.append(Spacer(1, inch))
        
        # Confidential notice
        confidential = Paragraph(
            "<b>CONFIDENTIAL</b><br/>"
            "This report contains sensitive security information. "
            "Distribution should be limited to authorized personnel only.",
            self.styles['Normal']
        )
        elements.append(confidential)
        
        # Page break
        elements.append(Spacer(1, inch))
        elements.append(Paragraph("Page 1", self.styles['Normal']))
        
        return elements
    
    def create_executive_summary(self, config):
        """Create executive summary section"""
        elements = []
        
        elements.append(Paragraph("EXECUTIVE SUMMARY", self.styles['Heading1']))
        elements.append(Spacer(1, 0.2*inch))
        
        # Get summary statistics
        total_findings = self.db.findings.count_documents({})
        critical_findings = self.db.findings.count_documents({'risk_level': 'critical'})
        high_findings = self.db.findings.count_documents({'risk_level': 'high'})
        
        summary_text = f"""
        This security assessment identified <b>{total_findings}</b> potential privilege escalation vectors 
        across the monitored systems. Among these, <b>{critical_findings}</b> were classified as critical 
        and <b>{high_findings}</b> as high risk, requiring immediate attention.
        
        The analysis employed advanced detection methodologies including AI-powered pattern recognition 
        and comprehensive system scanning to identify both known and emerging threats.
        
        <b>Key Recommendations:</b>
        • Prioritize mitigation of critical and high-risk findings
        • Implement continuous monitoring for privilege escalation attempts
        • Regular security awareness training for users
        • Periodic review of system permissions and access controls
        """
        
        summary_para = Paragraph(summary_text, self.styles['Normal'])
        elements.append(summary_para)
        elements.append(Spacer(1, 0.3*inch))
        
        return elements
    
    def create_findings_section(self, config):
        """Create detailed findings section"""
        elements = []
        
        elements.append(Paragraph("DETAILED FINDINGS", self.styles['Heading1']))
        elements.append(Spacer(1, 0.2*inch))
        
        # Get findings based on config
        query = {}
        if config.get('start_date'):
            query['created_at'] = {'$gte': config['start_date']}
        
        findings = list(self.db.findings.find(query).sort('risk_level', -1))
        
        for i, finding in enumerate(findings[:20]):  # Limit to top 20 findings
            elements.extend(self.create_finding_entry(finding, i+1))
            elements.append(Spacer(1, 0.1*inch))
        
        return elements
    
    def create_finding_entry(self, finding, index):
        """Create individual finding entry"""
        elements = []
        
        # Risk level color coding
        risk_colors = {
            'critical': colors.red,
            'high': colors.orange,
            'medium': colors.yellow,
            'low': colors.green
        }
        
        risk_color = risk_colors.get(finding['risk_level'], colors.black)
        
        # Finding header
        header_text = f"{index}. {finding['title']} - <font color='{risk_color}'>{finding['risk_level'].upper()}</font>"
        header = Paragraph(header_text, self.styles['FindingTitle'])
        elements.append(header)
        
        # Finding details table
        details_data = [
            ["Description:", finding['description']],
            ["Category:", finding.get('category', 'Unknown')],
            ["CVSS Score:", str(finding.get('cvss_score', 'N/A'))],
            ["Evidence:", finding.get('evidence', 'No evidence')[:200] + "..."],
            ["Mitigation:", finding.get('mitigation', 'No mitigation provided')]
        ]
        
        details_table = Table(details_data, colWidths=[1.5*inch, 5*inch])
        details_table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
        ]))
        
        elements.append(details_table)
        
        return elements
    
    def create_mitigation_section(self, config):
        """Create mitigation recommendations section"""
        elements = []
        
        elements.append(Paragraph("MITIGATION RECOMMENDATIONS", self.styles['Heading1']))
        elements.append(Spacer(1, 0.2*inch))
        
        recommendations = [
            "Implement principle of least privilege for all user accounts",
            "Regularly review and update system permissions",
            "Enable and monitor audit logs for privilege escalation attempts",
            "Apply security patches and updates promptly",
            "Conduct regular security awareness training",
            "Implement application whitelisting where appropriate",
            "Use security tools like Privileged Rapper Inc. for continuous monitoring"
        ]
        
        for rec in recommendations:
            elements.append(Paragraph(f"• {rec}", self.styles['Normal']))
            elements.append(Spacer(1, 0.05*inch))
        
        return elements
    
    def add_footer(self, canvas, doc):
        """Add footer to each page"""
        canvas.saveState()
        
        # Footer text
        footer_text = "GENERATED BY PRIVILEGED RAPPER INC. - CONFIDENTIAL"
        
        # Set font and draw footer
        canvas.setFont('Helvetica', 8)
        canvas.setFillColor(colors.gray)
        
        # Draw footer at bottom
        canvas.drawCentredString(doc.width/2.0, 0.5*inch, footer_text)
        
        # Add page number
        page_num = f"Page {doc.page}"
        canvas.drawRightString(doc.width + doc.rightMargin, 0.5*inch, page_num)
        
        canvas.restoreState()